<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Daftar_barang_masuk_model extends CI_Model
{
    public $table = 'barang_masuk';
    public $key = 'masuk_id';
    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }
    //get all data
    function get_daftar_barang_masuk()
    {
        $this->db->order_by($this->key, 'desc');
        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('pemasok','masuk_pemasok_id=pemasok_id');
        $this->db->order_by($this->key);
            $this->db->like('masuk_nofaktur', $q);
            $this->db->or_like('pemasok_nama', $q);
            $this->db->or_like('masuk_tanggal', $q);
            $this->db->or_like('masuk_tutup_buku', $q);
            $this->db->or_like('masuk_userinput', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function total_transaksi($masuk_id){
        $this->db->select('sum(detail_harga_satuan * detail_jumlah) as tot');
        $this->db->where('detail_masuk_id',$masuk_id);
        $this->db->group_by('detail_masuk_id');
        return $this->db->get('detail_masuk')->row();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('pemasok','masuk_pemasok_id=pemasok_id');
            $this->db->like('masuk_nofaktur', $q);
            $this->db->or_like('pemasok_nama', $q);
            $this->db->or_like('masuk_tanggal', $q);
            $this->db->or_like('masuk_tutup_buku', $q);
            $this->db->or_like('masuk_userinput', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    //Save Data
    public function save($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }
    //delete data
    public function delete($id)
    {
        $this->db->where('detail_masuk_id', $id);
        $this->db->delete('detail_masuk');

                $this->db->where($this->key, $id);
        $this->db->delete($this->table);
    }
    //Get data by id
    public function get_by_id($id){
        $this->db->where($this->key,$id);
        return $this->db->get($this->table)->row();
    }
    // update data
    function update($data,$id){
        $this->db->where($this->key, $id);
        $this->db->update($this->table, $data);
    }
    
}

/* End of file Daftar_barang_masuk_model.php */
/* Location: ./application/models/Daftar_barang_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator V1 06 Nov 2017 09:01:08 */
/* Copyright @ 2017 By Wanhar Azri S.Kom */