<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Menu_model extends CI_Model
{
    public $table = 'menu_makanan';
    public $key = 'menuid';
    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }
    //get all data
    function get_barang()
    {
        $this->db->order_by($this->key, 'desc');
        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->key);
            $this->db->like('katnama', $q);
            $this->db->or_like('menunama', $q);
            $this->db->or_like('menuharga', $q);
            $this->db->or_like('menusatuan', $q);
        $this->db->join('menu_kategori','menukatid=katid');
        $this->db->limit($limit, $start);
        return $this->db->get('menu_makanan')->result();
    }
    function caribahan($q = NULL) {
        $this->db->order_by('bahanid');
        $this->db->join('satuan','bahansatuanid=satuanid');
        $this->db->like('bahannama', $q);
        $this->db->or_like('satuannama', $q);
        return $this->db->get('menu_bahan')->result();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('katnama', $q);
            $this->db->or_like('menunama', $q);
            $this->db->or_like('menuharga', $q);
            $this->db->or_like('menusatuan', $q);
            $this->db->join('menu_kategori','menukatid=katid');
        $this->db->from('menu_makanan');
        return $this->db->count_all_results();
    }
    //Save Data
    public function save($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }
    //delete data
    public function delete($id)
    {
        $this->db->where($this->key, $id);
        $this->db->delete($this->table);
    }
    //Get data by id
    public function get_by_id($id){
        $this->db->where($this->key,$id);
        return $this->db->get($this->table)->row();
    }
    // update data
    function update($data,$id){
        $this->db->where($this->key, $id);
        $this->db->update($this->table, $data);
    }
    function get_kategori()
    {
        return $this->db->get('menu_kategori')->result();
    }
    function get_rak()
    {
        return $this->db->get('rak')->result();
    }

    //Generate Stok
    public function generate_stok($id){
        /*$query=$this->db->query("SELECT 
            `barang_stok_besar`, 
            `barang_stok_kecil`, 
            `barang_konversi`, 
            ((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`) AS all_stok, 
            floor(((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`) / `barang_konversi`) AS new_stok_besar, 
            MOD((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`,`barang_konversi`) AS new_stok_kecil 
            FROM `barang` 
        WHERE menuid=$id")->row();
        if(!empty($query)){
            $this->db->query("UPDATE barang SET barang_stok_besar=floor(((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`) / `barang_konversi`),barang_stok_kecil=(MOD((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`,`barang_konversi`)) WHERE menuid='$id'");
        }*/

        $this->db->query("UPDATE barang SET barang_stok_besar=floor(((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`) / `barang_konversi`),barang_stok_kecil=(MOD((`barang_stok_besar`*`barang_konversi`) + `barang_stok_kecil`,`barang_konversi`)) WHERE menuid='$id'");

    }
    
}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator V1 21 Oct 2017 07:12:17 */
/* Copyright @ 2017 By Wanhar Azri S.Kom */