<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Transaksi_model extends CI_Model
{
    public $table = 'transaksi';
    public $key = 'transaksi_id';
    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }
    //get all data
    function get_transaksi()
    {
        $this->db->order_by($this->key, 'desc');
        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('akun','transaksi_akun_id=akun_id');
        $this->db->order_by($this->key);
        $this->db->like('akun_nama', $q);
        $this->db->or_like('akun_jenis', $q);
        $this->db->or_like('transaksi_jumlah', $q);
        $this->db->or_like('transaksi_catatan', $q);
        $this->db->or_like('transaksi_tglinput', $q);
        $this->db->or_like('transaksi_userinput', $q);
        $this->db->limit($limit, $start);
        $this->db->order_by('transaksi_id','DESC');
        return $this->db->get($this->table)->result();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('akun','transaksi_akun_id=akun_id');
        $this->db->like('akun_nama', $q);
        $this->db->or_like('akun_jenis', $q);
        $this->db->or_like('transaksi_jumlah', $q);
        $this->db->or_like('transaksi_catatan', $q);
        $this->db->or_like('transaksi_tglinput', $q);
        $this->db->or_like('transaksi_userinput', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    //Save Data
    public function save($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }
    //delete data
    public function delete($id)
    {
        $this->db->where($this->key, $id);
        $this->db->delete($this->table);
    }
    //Get data by id
    public function get_by_id($id){
        $this->db->where($this->key,$id);
        $this->db->join('users','transaksi_userinput=username');
        return $this->db->get($this->table)->row();
    }
    // update data
    function update($data,$id){
        $this->db->where($this->key, $id);
        $this->db->update($this->table, $data);
    }
    function get_akun()
    {
        return $this->db->get('akun')->result();
    }
    
}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator V1 05 Dec 2017 11:27:40 */
/* Copyright @ 2017 By Wanhar Azri S.Kom */